language: csharp
os:
- osx
env:
  global:
  - Configuration=Release
install:
- wget -O MonoGame.pkg "http://teamcity.monogame.net/guestAuth/repository/download/MonoGame_PackageMacAndLinux/.lastSuccessful/MonoGame.pkg?branch_MonoGame=%3Cdefault%3E"
- sudo installer -pkg "MonoGame.pkg" -target /
script:
- nuget restore Samples-Linux.sln
- msbuild Platformer2D/Platforms/Linux/Platformer2D.csproj /p:Configuration=Release /v:d /t:Build
- msbuild NeonShooter/Platforms/Linux/NeonShooter.csproj /p:Configuration=Release /v:d /t:Build
